<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaRge25.Data\TaRge25Shop.Data.csproj" />
    <ProjectReference Include="..\TaRge25Shop.Core\TaRge25Shop.Core.csproj" />
  </ItemGroup>

</Project>
